import sharp from 'sharp';
import path from 'path';
import fs from 'fs';

const RAW_DIR = './raw_renders';
const OUT_DIR = './public/assets/items';
const OFFSETS_FILE = './src/item_offsets.generated.ts';

if (!fs.existsSync(OUT_DIR)) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
}

const ITEM_IDS = [
  'brass_sphere', 'cast_iron_bell', 'chasen_whisk', 'chashaku_scoop',
  'chawan_cup', 'coldbrew_flask', 'copper_caddy', 'dango_plate',
  'dango_stick', 'gotoku_trivet', 'incense_burner', 'kissa_toast',
  'kuro_mame_dome', 'matcha_montblanc', 'matcha_roll', 'mizuhiki_knot',
  'origami_dripper', 'shou_sugi_block', 'tetsubin_kettle', 'yokan_prism'
];

const TARGET_SIZE = 256;
const ITEM_DISPLAY_SIZE = 72;
const DEFAULT_OFFSET = 36;

function findAlphaBounds(data, width, height) {
  let top = height, bottom = -1;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (data[(y * width + x) * 4 + 3] > 10) {
        if (y < top) top = y;
        if (y > bottom) bottom = y;
        break;
      }
    }
  }
  return { top, bottom };
}

async function processImages() {
  if (!fs.existsSync(RAW_DIR)) return;
  const files = fs.readdirSync(RAW_DIR).filter(f => {
    const ext = path.extname(f).toLowerCase();
    return ext === '.png' || ext === '.jpg' || ext === '.jpeg';
  });

  const offsets = {};

  for (const file of files) {
    const filePath = path.join(RAW_DIR, file);
    const baseName = path.parse(file).name;
    const targetPath = path.join(OUT_DIR, `${baseName}.png`);

    console.log(`Processing: ${file}`);

    // FALL 1: Hintergrund (Seitenverhältnis erhalten, Breite 720)
    if (baseName.startsWith('bg_')) {
      await sharp(filePath)
        .resize(720, null, { fit: 'inside' })
        .png({ quality: 90 })
        .toFile(targetPath);
      continue;
    }

    // FALL 2: Regal-Leiste (Freistellen, aber breites Seitenverhältnis beibehalten)
    if (baseName.startsWith('shelf_')) {
      const image = sharp(filePath).ensureAlpha();
      const { data, info } = await image.raw().toBuffer({ resolveWithObject: true });

      for (let i = 0; i < data.length; i += 4) {
        const dist = Math.sqrt((255 - data[i]) ** 2 + (255 - data[i + 1]) ** 2 + (255 - data[i + 2]) ** 2);
        if (dist < 18) data[i + 3] = 0;
        else if (dist < 38) data[i + 3] = Math.floor(((dist - 18) / 20) * 255);
      }

      await sharp(data, { raw: { width: info.width, height: info.height, channels: 4 } })
        .trim()
        .resize(608, 184, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png({ compressionLevel: 9 })
        .toFile(targetPath);
      continue;
    }

    // FALL 3: Goods & UI-Icons (Freistellen, 256x256, Bottom-Offset berechnen)
    if (!ITEM_IDS.includes(baseName)) continue;

    const image = sharp(filePath).ensureAlpha();
    const { data, info } = await image.raw().toBuffer({ resolveWithObject: true });

    for (let i = 0; i < data.length; i += 4) {
      const dist = Math.sqrt((255 - data[i]) ** 2 + (255 - data[i + 1]) ** 2 + (255 - data[i + 2]) ** 2);
      if (dist < 18) data[i + 3] = 0;
      else if (dist < 38) data[i + 3] = Math.floor(((dist - 18) / 20) * 255);
    }

    // Alpha-Bounds im Raw-Source bestimmen (VOR dem Trim)
    const bounds = findAlphaBounds(data, info.width, info.height);

    // Bottom-Offset: Pixel vom untersten sichtbaren Pixel zur unteren Kante des Raw-Bildes
    const trimBottom = bounds.bottom >= 0 ? (info.height - 1 - bounds.bottom) : 0;

    // In Design-Koordinaten umrechnen (72px-Display)
    const offsetDesign = info.height > 0
      ? parseFloat((trimBottom * (ITEM_DISPLAY_SIZE / info.height)).toFixed(2))
      : DEFAULT_OFFSET;

    offsets[baseName] = offsetDesign;
    console.log(`  ${baseName}: rawH=${info.height} bottomRow=${bounds.bottom} trimBottom=${trimBottom}px → ${offsetDesign}px design`);

    // Defringing + Trim + Resize auf 256x256
    await sharp(data, { raw: { width: info.width, height: info.height, channels: 4 } })
      .trim()
      .resize(TARGET_SIZE, TARGET_SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .png({ compressionLevel: 9 })
      .toFile(targetPath);
  }

  // Fehlende Items auf Default setzen
  for (const id of ITEM_IDS) {
    if (!(id in offsets)) {
      offsets[id] = DEFAULT_OFFSET;
      console.log(`  ${id}: missing raw file, using default ${DEFAULT_OFFSET}px`);
    }
  }

  // Offsets-Datei schreiben
  const lines = ITEM_IDS
    .map(id => `  ${id}: ${offsets[id]}`)
    .join(',\n');

  const tsContent = `// Auto-generated by scripts/process_assets.js — do not edit manually
export const ITEM_BOTTOM_OFFSETS: Record<string, number> = {
${lines}
};
`;

  fs.writeFileSync(OFFSETS_FILE, tsContent, 'utf-8');
  console.log(`\nWrote ${OFFSETS_FILE}`);
  console.log('Asset Processing Complete.');
}

processImages();
