// Auto-generated by scripts/process_assets.js — do not edit manually
export const ITEM_BOTTOM_OFFSETS: Record<string, number> = {
  brass_sphere: 15.19,
  cast_iron_bell: 36,
  chasen_whisk: 36,
  chashaku_scoop: 9.28,
  chawan_cup: 27.84,
  coldbrew_flask: 36,
  copper_caddy: 36,
  dango_plate: 14.34,
  dango_stick: 36,
  gotoku_trivet: 10.69,
  incense_burner: 23.06,
  kissa_toast: 36,
  kuro_mame_dome: 18,
  matcha_montblanc: 33.19,
  matcha_roll: 29.53,
  mizuhiki_knot: 36,
  origami_dripper: 25.59,
  shou_sugi_block: 36,
  tetsubin_kettle: 29.53,
  yokan_prism: 25.59
};

// Lichte Weite der Nische je Hintergrund, gemessen am fertigen PNG (Anteil der Bildbreite).
export const BG_CAVITY_RATIOS: Record<string, number> = {
  bg_kissa_niche: 0.6458,
  bg_kissa_niche_mid: 0.6458,
  bg_kissa_niche_wide: 0.8167,
  bg_plaster: 0.8958
};
