// Auto-generated by scripts/process_assets.js — do not edit manually
export const ITEM_BOTTOM_OFFSETS: Record<string, number> = {
  chawan_cup: 36,
  chochin: 36,
  dango_stick: 36,
  daruma: 36,
  furoshiki: 36,
  incense_burner: 36,
  kissa_toast: 36,
  kokeshi: 36,
  maneki_neko: 36,
  matcha_roll: 36,
  omamori: 36,
  onigiri: 34.69,
  koinobori: 36,
  sake_tokkuri: 36,
  sensu_fan: 36,
  temari: 36,
  tetsubin_kettle: 36,
  torii_gate: 6.19,
  wagashi: 36,
  yokan_prism: 36
};

// Lichte Weite der Nische je Hintergrund, gemessen an der fertigen Textur (Anteil der Bildbreite).
export const BG_CAVITY_RATIOS: Record<string, number> = {
  bg_kissa_niche: 0.6451,
  bg_kissa_niche_mid: 0.6451,
  bg_kissa_niche_wide: 0.8167,
  bg_kissa_room: 0.4764,
  bg_plaster: 0.9306,
  bgl_niche_frame: 0.5592
};

// Lichte Nische als Rechteck in Bildanteilen: x ist die Mitte, y die Oberkante.
export const BG_CAVITY_RECTS: Record<string, { x: number; y: number; w: number; h: number }> = {
  bgl_niche_frame: { x: 0.5029, y: 0.1166, w: 0.5592, h: 0.7678 }
};

// Aeussere Kontur eines freistehenden Rahmens in Bildanteilen.
export const BG_FRAME_RECTS: Record<string, { x: number; y: number; w: number; h: number }> = {
  bgl_niche_frame: { x: 0.5, y: 0.0682, w: 0.6819, h: 0.8674 }
};

// Auflageflaeche eines Regalbretts als Anteil seiner Bildhoehe.
export const SHELF_PLATFORM_RATIOS: Record<string, number> = {
  shelf_wood: 0.6769
};

// Dateiendung der erzeugten Texturen. Der Loader haengt sie an den Asset-Key an.
export const ASSET_EXT = 'webp';

// Alle Texturen, die tatsaechlich in public/assets/items/ liegen.
export const AVAILABLE_ASSETS: ReadonlySet<string> = new Set([
  'bg_kissa_niche',
  'bg_kissa_niche_mid',
  'bg_kissa_niche_wide',
  'bg_kissa_room',
  'bg_plaster',
  'bgl_cat',
  'bgl_clouds',
  'bgl_dog',
  'bgl_hills',
  'bgl_lanterns',
  'bgl_meadow',
  'bgl_niche_frame',
  'bgl_sky',
  'brass_sphere',
  'btn_hammer',
  'btn_shuffle',
  'btn_undo',
  'cast_iron_bell',
  'chasen_whisk',
  'chashaku_scoop',
  'chawan_cup',
  'chochin',
  'coldbrew_flask',
  'copper_caddy',
  'dango_plate',
  'dango_stick',
  'daruma',
  'furoshiki',
  'fx_match_burst',
  'gotoku_trivet',
  'incense_burner',
  'kissa_toast',
  'kokeshi',
  'kuro_mame_dome',
  'maneki_neko',
  'matcha_montblanc',
  'matcha_roll',
  'mizuhiki_knot',
  'omamori',
  'onigiri',
  'origami_dripper',
  'sake_tokkuri',
  'sensu_fan',
  'shelf_wood',
  'shou_sugi_block',
  'temari',
  'tetsubin_kettle',
  'torii_gate',
  'ui_card_hinoki',
  'ui_card_kuro',
  'ui_star',
  'ui_star_empty',
  'wagashi',
  'yokan_prism'
]);
