// Auto-generated by scripts/process_assets.js — do not edit manually
export const ITEM_BOTTOM_OFFSETS: Record<string, number> = {
  chawan_cup: 36,
  chochin: 36,
  dango_stick: 36,
  daruma: 36,
  furoshiki: 36,
  incense_burner: 36,
  kissa_toast: 36,
  kokeshi: 36,
  maneki_neko: 36,
  matcha_roll: 36,
  omamori: 36,
  onigiri: 34.69,
  koinobori: 36,
  sake_tokkuri: 36,
  sensu_fan: 36,
  temari: 36,
  tetsubin_kettle: 36,
  torii_gate: 6.19,
  wagashi: 36,
  yokan_prism: 36
};

// Lichte Weite der Nische je Hintergrund, gemessen an der fertigen Textur (Anteil der Bildbreite).
export const BG_CAVITY_RATIOS: Record<string, number> = {

};

// Lichte Nische als Rechteck in Bildanteilen: x ist die Mitte, y die Oberkante.
export const BG_CAVITY_RECTS: Record<string, { x: number; y: number; w: number; h: number }> = {
  bgl_cabinet_6row: { x: 0.4983, y: 0.0115, w: 0.9042, h: 0.9599 }
};

// Aeussere Kontur eines freistehenden Rahmens in Bildanteilen.
export const BG_FRAME_RECTS: Record<string, { x: number; y: number; w: number; h: number }> = {
  bgl_cabinet_6row: { x: 0.501, y: 0.0107, w: 0.9215, h: 0.9813 }
};

// Auflageflaeche eines Regalbretts als Anteil seiner Bildhoehe.
export const SHELF_PLATFORM_RATIOS: Record<string, number> = {

};

// Y-Verhaeltnisse der Brettoberflaechen je Cabinet-Variante (0..1 relativ zur Bildhoehe).
export const CABINET_SHELF_RATIOS: Record<string, number[]> = {
  bgl_cabinet_6row: [0.0333, 0.1333, 0.2754, 0.4147, 0.5532, 0.6917, 0.8298, 0.9357]
};

// Dateiendung der erzeugten Texturen. Der Loader haengt sie an den Asset-Key an.
export const ASSET_EXT = 'webp';

// Alle Texturen, die tatsaechlich in public/assets/items/ liegen.
export const AVAILABLE_ASSETS: ReadonlySet<string> = new Set([
  'bgl_cabinet_6row',
  'bgl_clouds',
  'bgl_hills',
  'bgl_lanterns',
  'bgl_meadow',
  'bgl_sky',
  'btn_hammer',
  'btn_shuffle',
  'btn_undo',
  'chawan_cup',
  'chochin',
  'dango_stick',
  'daruma',
  'furoshiki',
  'fx_match_burst',
  'incense_burner',
  'kissa_toast',
  'kokeshi',
  'maneki_neko',
  'matcha_roll',
  'omamori',
  'onigiri',
  'sake_tokkuri',
  'sensu_fan',
  'temari',
  'tetsubin_kettle',
  'torii_gate',
  'ui_card_hinoki',
  'ui_card_kuro',
  'ui_star',
  'ui_star_empty',
  'wagashi',
  'yokan_prism'
]);
